apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgagroal.fullname" . }}
  labels:
    {{- include "pgagroal.labels" . | nindent 4 }}
data:
  pgagroal.conf.template: |
    [pgagroal]
    host = ${PGAGROAL_HOST}
    port = ${PGAGROAL_PORT}
    unix_socket_dir = /tmp/

    log_type = console
    log_level = ${PGAGROAL_LOG_LEVEL}

    max_connections = ${MAX_CONNECTIONS}
    idle_timeout = 600
    validation = off
    allow_unknown_users = true

    pipeline = auto
    ev_backend = epoll
    keep_alive = on
    nodelay = on
    blocking_timeout = 30
    {{- if .Values.metrics.enabled }}

    metrics = {{ .Values.metrics.port }}
    {{- end }}

    [primary]
    host = ${PG_BACKEND_HOST}
    port = ${PG_BACKEND_PORT}
  pgagroal_hba.conf.template: |
    #
    # pgagroal host-based authentication
    #
    # TYPE  DATABASE  USER  ADDRESS      METHOD
    #
    host    all       all   all          all
