{{- if and .Values.pgexporter.enabled .Values.pgexporter.credentials.create (not .Values.pgexporter.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgagroal.pgexporter.fullname" . }}
  labels:
    {{- include "pgagroal.pgexporter.labels" . | nindent 4 }}
type: Opaque
data:
  PGEXPORTER_USER: {{ .Values.pgexporter.credentials.username | b64enc | quote }}
  PGEXPORTER_PASSWORD: {{ required "pgexporter.credentials.password is required when pgexporter.enabled and pgexporter.credentials.create are set (or use pgexporter.credentials.existingSecret)" .Values.pgexporter.credentials.password | b64enc | quote }}
{{- end }}
