apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgagroal.fullname" . }}
  labels:
    {{- include "pgagroal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pooler
      port: {{ .Values.service.port }}
      targetPort: pooler
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.observability.sidecar.enabled }}
    - name: obs-metrics
      port: {{ .Values.observability.sidecar.port }}
      targetPort: obs-metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "pgagroal.selectorLabels" . | nindent 4 }}
