kind: policy
name: {{ include "pgagroal.policy.name" . }}
description: Grants the pgAgroal identity reveal access to its credentials secret
tags:
  {{- include "pgagroal.tags" . | nindent 2 }}
bindings:
  - permissions:
      - reveal
    principalLinks:
      - //gvc/{{ .Values.global.cpln.gvc }}/identity/{{ include "pgagroal.identity.name" . }}
targetKind: secret
targetLinks:
  - //secret/{{ include "pgagroal.credentials.name" . }}
  {{- if .Values.tls.enabled }}
  - //secret/{{ include "pgagroal.tls.cert.name" . }}
  - //secret/{{ include "pgagroal.tls.key.name" . }}
  {{- if .Values.tls.mutualTLS }}
  - //secret/{{ include "pgagroal.tls.ca.name" . }}
  {{- end }}
  {{- end }}
