{{- if .Values.tls.enabled }}
kind: secret
name: {{ include "pgagroal.tls.cert.name" . }}
description: Elevarq pgAgroal frontend TLS server certificate (PEM)
tags:
  {{- include "pgagroal.tags" . | nindent 2 }}
type: opaque
data:
  encoding: plain
  payload: |-
    {{- .Values.tls.cert | nindent 4 }}
---
kind: secret
name: {{ include "pgagroal.tls.key.name" . }}
description: Elevarq pgAgroal frontend TLS server private key (PEM)
tags:
  {{- include "pgagroal.tags" . | nindent 2 }}
type: opaque
data:
  encoding: plain
  payload: |-
    {{- .Values.tls.key | nindent 4 }}
{{- if .Values.tls.mutualTLS }}
---
kind: secret
name: {{ include "pgagroal.tls.ca.name" . }}
description: Elevarq pgAgroal frontend TLS client CA bundle (PEM)
tags:
  {{- include "pgagroal.tags" . | nindent 2 }}
type: opaque
data:
  encoding: plain
  payload: |-
    {{- .Values.tls.caCert | nindent 4 }}
{{- end }}
{{- end }}
