kind: secret
name: {{ include "pgagroal.credentials.name" . }}
description: Elevarq pgAgroal backend PostgreSQL password
tags:
  {{- include "pgagroal.tags" . | nindent 2 }}
type: dictionary
data:
  pg-password: {{ .Values.auth.password | quote }}
